name: Deploy Azure Infra

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ARM template
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: rg-azure-s3-to-azsql-dev
        template: arm/dummy.json
    - name: Deploy Key Vault
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: rg-azure-s3-to-azsql-dev
        template: arm/keyvault.json
        parameters: arm/parameters/dev.parameters.json

